# Don't retry jobs if they fail
restart-times: 2

# Specify custom job submission wrapper
# cluster: "../scripts/LSF_cluster_job.py"
cluster: "../scripts/SLURM_cluster_job.py"

# Specify custom job status command wrapper
cluster-status: "../scripts/SLURM_cluster_status.py"  # comment out if int SLURM

# Dont submit/check-job-status more then x times per second
max-jobs-per-second: 1000
max-status-checks-per-second: 1

# Max number of jobs to submit at one time to queue
jobs: 1000

# Max number of cores that can be use in parallel for all rules/jobs
local-cores: 1000

# Re-run all jobs the output of which is recognized as incomplete.
rerun-incomplete: true  # recommended for cluster submissions

# Stop if independent jobs fails
keep-going: false

# Only re run if the output is newer that the input
# rerun-triggers: mtime
