import os
import pandas as pd

##### Set up #####
configfile: "./config/main_config.yaml"

# Make sure the dataset exists and a workflow for creating a so object also
supported_datasets = {
    "jackson": "0_make_so_jackson/Snakefile"
}
dataset_name = os.path.basename(config["root"])

##### Define path variables form config #####
root=config["root"]
prediction_target=config["prediction_target"]
normalized_with=f"normalized_with_{config['normalize_with']}"
split_how=config["split_how"]
mlflow_on_remote_server=config["mlflow_on_remote_server"]

##### Helper functions #####
include: "rules/helper_functions.smk"

##### Load other rules #####
# Useful when wanting to run the workflow in chunks.

# Make folder structure and default config files
include: "rules/make_folder_structure.smk"

# Normalize data
include: "rules/normalize_all_folds.smk"

# Gen datasets
include: "rules/gen_all_graphs.smk" # Generates all concept graph datasets.

# Attribute graphs
include: "rules/gen_all_attributed_graphs.smk"

# Pretrain
include: "rules/pretrain_all.smk" # Pretrains all models

# Select pretrain models
include: "rules/select_best_pretrain_models.smk"
include: "rules/collect_concept_sets.smk"

# Train
include: "rules/train_all.smk" # Train all models.
# include: "rules/train_end2end_gcls.smk" # Train al the end2end models.

# Train baselines
# include: "rules/train_all_space_gm.smk" # Run all the space gm training configurations.

##### Load workflow rules #####
# Include baselines
# include: "00_baselines_non_geom/Snakefile"

# Make so object out of raw Jakson dataset.
include: supported_datasets[dataset_name]

# Filter samples based on defined concepts
include: "1_filter_samples/Snakefile"

# Split into train test and val.
include: "2_split_samples/Snakefile"

# Normalize data as specified in the config.
include: "3_normalize/Snakefile"

# Generate datasets
include: "4_generate_graph_datasets/Snakefile"

# Attribute graphs and saves them as python geometric Data class objects
include: "5_attribute/Snakefile"

# Pretrain gnn models for the graph concept learner and
include: "6_pretrain/Snakefile"

# Generate tables with results and get paths to best models
include: "7_model_selection/Snakefile"

# train the graph concept learner.
include: "8_train/Snakefile"

# Select best GCL models
include: "9_model_selection/Snakefile"
